ShopApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path("register/", RegistretionUser.as_view(), name="register"),
    path("register/verify/", VerifyCode.as_view(), name="verify_code"),
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("otp_delete/",delete_otp_codes.as_view(),name="otp-del")
]

apps/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:category_slug>/", HomeView.as_view(), name="category"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

__all__ = ['Category','Product']

class Category(models.Model):
    name = models.CharField(max_length=200,)
    slug = models.CharField(max_length=200,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d')
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2)
    amount = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        pass

    def __str__(self):
        return self.name

    def is_avalible(self):
        return True if self.amount == 0 else False

apps/home/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views import View
from .models import *
from apps.cart.utils import Cart

__all__ = [
    'HomeView',
    'ProductDetailView',
]

class HomeView(ListView):
    template_name = 'home/index.html'
    context_object_name = 'products'
    ordering = ('created',)
    paginate_by = 24
    
    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        products = Product.objects.all()
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            return products.filter(category=category)
        else:
            return products

class ProductDetailView(DetailView):
    template_name = 'home/detail.html'
    model = Product
    context_object_name = 'product'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            count_item = Cart(self.request.user.id).count_item(context['object'].id)
            if count_item:
                context['count_item'] = count_item

        return context

apps/home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block head-custom %}
    <link rel="stylesheet" href="{% static 'styles/detail.css' %}">
{% endblock head-custom %}

{% block title %}{{product.name}}{% endblock title %}

{% block body %}
    <div class="col-12 d-flex p-2">
        <div class="col-4 text-start">
            <img class="img-thumbnail col-12 p-2 w-75" src="{{ product.image.url }}" alt="">
            <h2 class="text-start  w-75" style="font-size: 1.5vw;">{{product.name}}</h2>
            <p class="lead badge bg-primary" style="font-size: 0.8vw;">{{ product.category }}</p>
        </div>

        
        <div class="col-4">
            <p class=" font-weight-normal" style="text-align: justify;font-size: 1vw;">{{product.description | safe}}</p>
        </div>
        
        
        <div class="col-4">
            <div id="box-buy" class="bg-white">
                <span><i class="fa-solid fa-shield text-warning"></i> 3 Day Waranty</span>
                <hr>
                <span>
                    {% for num in product.amount|make_list  %}<i class="text-primary fa-solid fa-{{ num }}"></i>{% endfor %} Available in stock
                </span>
                <hr>
                <span><i class="fa-solid fa-dollar-sign text-success"></i> {{ product.price | intcomma }}</span>
                <hr>

                <div class="btn-group" id='g-b'>
                {% if count_item %}
                    <button onclick="SubtractItem({{ product.id }})" class="btn btn-danger" id="subtract-product">
                        {% if count_item == 1 %}
                            <i class="fa-solid fa-trash"></i>
                        {% else %}
                            <i class="fa-solid fa-minus"></i>
                        {% endif %}
                    </button>
                    <button class="btn btn-secondary" style="cursor: default;" id="p-c-{{ product.id }}">{{ count_item }}</button>
                    <button onclick="AddItem({{ product.id }})"  class="btn btn-success"><i class="fa-solid fa-plus"></i></button>
                {% else %}
                    {% if request.user.is_authenticated %}
                        <button onclick="AddItem({{ product.id }})"  class="btn btn-success"><i class="fa-solid fa-plus"></i></button>
                    {% else %}
                        <a href="{% url 'account:login' %}"  class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
                    {% endif %}
                {% endif %}
                </div>

            </div>
        </div>
    </div>

<script src="{% static 'script/cart/edit_order.js' %}"></script>
<script src="{% static 'script/cart/in_detail.js' %}"></script>
{% endblock body %}

apps/home/templates/home/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Home{% endblock title %}

{% block body %}
    <div class="d-flex flex-wrap justify-content-around">
        {% for product in products %}
        <div class="col-2 m-3 p-3 border border-secondary rounded">
            <a href="{% url 'home:detail' product.slug%}">
                <img class="img-thumbnail col-12 p-2" src="{{ product.image.url }}" alt="">
                <h2 class="text-center" style="font-size: 1vw;">{{product.name | truncatewords:10}}</h2>
                <div class="d-flex justify-content-between p-2">
                    <span class="lead" style="font-size: 1vw;"><i class="fa-solid fa-dollar-sign text-success"></i> {{ product.price | intcomma }}</span>
                    <span class="lead badge bg-primary" style="font-size: 0.8vw;">{{ product.category }}</span>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">    
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %} tabindex="-1">Previous</a>
            </li>
            {% for p in paginator %}
                <li class="page-item {% if p.number == page_obj.number %}active{% endif %}"><a class="page-link" href="{{ request.path }}?page={{p.number}}">{{ p.number }}</a></li>
            {% endfor %}

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a>
            </li>
        </ul>
    </nav>
    {% endif %}

{% endblock body %}