ShopApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path("checkoout/", CheckoOutView.as_view(), name="checkout"),
    path("checkout/edit/", EditItemView.as_view(), name="edit"),
]

apps/order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('payment/',PaymentView.as_view(),name='payment'),
    path('payment/pay/',PayView.as_view(),name='pay'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/models.py
from django.db import models
from apps.home.models import Product
from apps.account.models import User

__all__  = [
    'CartSession',
    'ItemSession'
]
class ItemSession(models.Model):
    cart = models.ForeignKey('CartSession',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    count = models.PositiveIntegerField(default=0)
    craeted = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.cart) + '-' + str(self.product)

class CartSession(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    craeted = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

    @property
    def total_price(self):
        prices = 0
        order_items = ItemSession.objects.filter(cart=self)
        for item in order_items:
            prices += item.product.price * item.count

        return prices

    @property
    def items(self):
        items = ItemSession.objects.filter(cart=self).order_by('craeted',)
        return items

apps/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View
from apps.home.models import Product
from .models import *
from .utils import Cart
import json

__all__ = [
    'CheckoOutView',
    'EditItemView'
]

class CheckoOutView(LoginRequiredMixin,View):
    def get(self,request):
        cart = CartSession.objects.filter(user=request.user)
        if cart.exists():
            cart = cart.get()
            return render(request,'cart/checkout.html',{'items':cart.items,'cart_detail':cart})
        else:
            return render(request,'cart/checkout.html')

class EditItemView(LoginRequiredMixin,View):
    def post(self,request):
        data = json.load(request)
        type = data['type']
        product_id = data['product_id']

        cart = Cart(request.user.id)
        if type == "add":
            count_product = Product.objects.get(id=product_id).amount
            if count_product == cart.count_item(product_id):
                return JsonResponse(
                            {
                                'status':'error',
                                'code':'404'
                            }
                            )
            cart.add_item(product_id)
        elif type == "subtract":
            try:
                cart.subtract_item(product_id)
            except:
                return JsonResponse({'status':'error','code':'404'})

        
        return JsonResponse(
            {
                'status':'ok',
            }
            )

apps/cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block head-custom %}
    <link rel="stylesheet" href="{% static 'styles/order.css' %}">
{% endblock head-custom %}

{% block title %}CheckOut Products{% endblock title %}

{% block body %}
{% if items %}
<table class="table border border-2">
    <thead class='table-dark'>
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Count</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in items %}
        <tr id="t-{{item.product.id}}">
            <td colspan='1' scope="row" class="text-medium">
              <img src={{item.product.image.url}} class='img-thumbnail rounded' width='8%'> 
              {{ item.product.name }}
            </td>
            <td colspan='1'> 
              <div class="btn-group border border-2 rounded">
                    <button onclick="SubtractItem({{ item.product.id }})" id="subtract-{{ item.product.id }}" class="btn text-danger">
                      {% if item.count > 1 %}
                        <i class="fa-solid fa-minus"></i>
                      {% else %}
                        <i class="fa-solid fa-trash"></i>
                      {% endif %}
                    </button>
                  <button class="btn btn-show">
                    <span id="p-c-{{item.product.id}}" class='text-danger num-bold'>{{item.count}}</span>
                  </button>
                  <button id="add-{{ item.product.id }}" onclick="AddItem({{ item.product.id }})" class="btn text-danger"><i class="fa-solid fa-plus"></i></button>
              </div>
            </td>
            <td colspan='1' class="text-secondary text-medium">
              <i class="fa-solid fa-dollar-sign"></i> <span id="p-p-{{item.product.id}}">{{ item.product.price | intcomma }}</span>
            </td>
        </tr>
    {% endfor %}
        <tr class="table-primary">
          <td colspan='2' class="p-2 text-bold">Total</td>
          <td colspan='1' class="p-2 text-bold text-success">
            <i class="fa-solid fa-dollar-sign"></i> <span id="total-price">{{ cart_detail.total_price | intcomma }}</span>
          </td>
        </tr>
      </tbody>
    </table>
    <hr>
    <a href="{% url 'order:payment' %}" id="p-btn" class="btn btn-success col-12">Payment</a>
</div>
{% else %}
<div id="empty">
  <i class="text-danger fa-solid fa-xmark"></i>
  <div>Cart Is Empty</div>
</div>

{% endif %}
<script src="{% static 'script/cart/edit_order.js' %}"></script>
<script src="{% static 'script/cart/in_checkout.js' %}"></script>
{% endblock body %}