ShopApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('payment/',PaymentView.as_view(),name='payment'),
    path('payment/pay/',PayView.as_view(),name='pay'),
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('profile/',ProfileView.as_view(),name='profile'),
    path('address/',AddressesView.as_view(),name='addresses'),
    path('address/create/',CreateAddresView.as_view(),name='create-address'),
    path('address/delete/<pk>/',DeleteAddressView.as_view(),name='delete-address'),
    path('order/',OredersView.as_view(),name='orders'),
    path('order/<pk>/',OrederDetailView.as_view(),name='order'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/models.py
from django.db import models
from apps.home.models import Product
from apps.account.models import User

__all__ = [
    'OrderItem',
    'OrderDetail',
    'PaymentDetail',
]

class OrderItem(models.Model):
    order = models.ForeignKey('OrderDetail',on_delete=models.CASCADE,related_name='orders')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    count = models.PositiveIntegerField(default=0)
    craeted = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.order) + '-' + str(self.product)

class OrderDetail(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='order')
    address = models.ForeignKey('user.address',on_delete=models.DO_NOTHING)
    craeted = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id) +  '-' + str(self.user)

    def total(self):
        prices = 0
        order_items = OrderItem.objects.filter(order=self)
        for item in order_items:
            prices += item.product.price * item.count
        
        return prices
    
    def items(self):
        items = OrderItem.objects.filter(order=self).order_by('craeted',)
        return items
    
    def payment_stat(self):
        return PaymentDetail.objects.get(order=self).status

class PaymentDetail(models.Model):
    STATUS_CHOICES =(
        ("a", "Await"),
        ("p", "paid")
    )

    status = models.CharField(max_length=1,choices=STATUS_CHOICES,default='a')
    order = models.ForeignKey(OrderDetail,on_delete=models.CASCADE,related_name='payment')
    craeted = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id) + '-' + str(self.order)

apps/user/models.py
from django.db import models
from apps.account.models import User
# Create your models here.
class Address(models.Model):
    to = models.ForeignKey(User,on_delete=models.CASCADE)
    city = models.CharField(max_length=20)
    short_address = models.CharField(max_length=120)
    no = models.PositiveBigIntegerField()
    unit = models.PositiveBigIntegerField()
    zip_code = models.PositiveBigIntegerField()

    def __str__(self):
        return self.short_address + '-' + str(self.zip_code)

    @property
    def full_address(self):
        address = self.city + ',' + self.short_address + ',N.o ' + str(self.no) + ',Unit ' + str(self.unit)
        return address

apps/user/forms.py
from django import forms
from apps.account.models import User
from .models import Address

__all__ = [
    'UserProfileForm',
    'UserCreateAddressForm'
]

class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['phone_number'].disabled = True
        self.fields['email'].disabled = True

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ('full_name','phone_number','email','defualt_address')

class UserCreateAddressForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Address
        exclude  = ('to',)

apps/order/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.cart.models import CartSession
from .utils import OrderManage
from django.contrib import messages
from apps.cart.models import CartSession

__all__ = [
    'PaymentView',
    'PayView'
]

class PaymentView(LoginRequiredMixin,View):
    def get(self,request):
        total_price = CartSession.objects.get(user=request.user.id).total_price
        return render(request,'order/payment.html',{'total_price':total_price})

class PayView(LoginRequiredMixin,View):
    def get(self,request):
        way = request.GET.get('way')
        match way:
            case 'paytest':
                order = OrderManage(request.user)
                cart = CartSession.objects.get(user=request.user)
                if not request.user.defualt_address:
                    messages.warning(request,'Please Set Address Defualt',extra_tags='warning')
                    return redirect('user:profile')
                order_ = order.CreateOreder(cart.items)
                messages.success(request,'The order is pending payment',extra_tags='warning')
                order.OrderPaid(order_)
                messages.success(request,'The payment of the order was successfully completed',extra_tags='success')
                cart.delete()
                return redirect('home:index')

apps/user/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import UpdateView,CreateView,ListView,DetailView,DeleteView
from apps.account.models import User
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import *
from .models import Address
from django.contrib import messages
from apps.order.models import OrderDetail,PaymentDetail

__all__ = [
    'ProfileView',
    'AddressesView',
    'DeleteAddressView',
    'CreateAddresView',
    'OredersView',
    'OrederDetailView',
]

class ProfileView(LoginRequiredMixin,UpdateView):
    template_name = 'user/profile.html'
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profile')

    def get_object(self):
        return User.objects.get(id=self.request.user.id)
    
    def form_valid(self, form):
        messages.success(self.request, "Profile Updated",extra_tags='success')
        return super().form_valid(form)

class AddressesView(LoginRequiredMixin,ListView):
    template_name = 'user/addresses.html'
    context_object_name = 'addresses'

    def get_queryset(self):
        addresses = Address.objects.filter(to=self.request.user)

        return addresses

class DeleteAddressView(LoginRequiredMixin,DeleteView):
    model = Address
    success_url = reverse_lazy('user:addresses')
    template_name = 'user/delete_address.html'

    def form_valid(self, form):
        messages.success(self.request,'Address Deleted',extra_tags='info')
        return super().form_valid(form)


class CreateAddresView(LoginRequiredMixin,CreateView):
    model = Address
    form_class = UserCreateAddressForm
    template_name = 'user/create_address.html'
    success_url = reverse_lazy('user:addresses')

    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.to = self.request.user

        return super().form_valid(form)

class OredersView(LoginRequiredMixin,ListView):
    template_name = 'user/orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        orders = OrderDetail.objects.filter(user=self.request.user)

        return orders
    


class OrederDetailView(LoginRequiredMixin,DetailView):
    template_name = 'user/order_detail.html'
    model = OrderDetail
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = context['order'].items

        return context

apps/user/templates/user/addresses.html
{% extends 'base.html' %}

{% block title %}Addresses{% endblock title %}

{% block body %}
    {% if addresses %}
        <div class="d-flex flex-wrap">
            {% for address in addresses %}
                <div class="card  col-6 p-2 bg-light border-0">
                    <div class="card-body bg-secondary text-light">
                        <p><i class="fa-solid fa-road"></i> {{ address.full_address }}</p>
                        <hr>
                        <div>
                            <span class="me-5"><i class="fa-solid fa-location-dot"></i> {{ address.city }}</span>
                            <span class="me-5"><i class="fa-solid fa-signs-post"></i> {{ address.zip_code }}</span>
                            {% if request.user.defualt_address == address %}
                                <span class="badge badge-pill badge-primary bg-primary">Defualt</span>
                            {% endif %}
                        </div>
                    </div>
                    
                    <a href="{% url 'user:delete-address' address.id %}" class="btn btn-danger">Delete</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
    <div class="text-center">
        <i class="text-danger fa-solid fa-xmark" style="font-size: 15vw;"></i>
        <p class="display-5">Don't Have Address</p>
    </div>
    {% endif %}

    <hr>
    <a href="{% url 'user:create-address' %}" class="btn btn-success col-12">Add New Address</a>
        
{% endblock body %}

apps/user/templates/user/create_address.html
{% extends 'base.html' %}

{% block title %}Addresses{% endblock title %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ADD" class="btn btn-success">
    </form>
{% endblock body %}

apps/user/templates/user/delete_address.html
{% extends 'base.html' %}

{% block title %}Addresses{% endblock title %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        Are You Sure?<a href="{% url 'user:addresses' %}" class="btn btn-secondary">No</a><input type="submit" class="btn btn-danger" value="Yes">
        
    </form>
{% endblock body %}

apps/user/templates/user/order_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Order {{ order.id }}{% endblock title %}

{% block body %}


<div>
    Your Order Created At {{ order.craeted | naturaltime }} and You 
    {% if order.payment_stat == 'a' %}<strong class="text-danger">Don't Paid</strong>
    {% elif order.payment_stat == 'p' %}<strong class="text-success">Paid</strong>{% endif %} It.
        
</div>
<hr>
<table class="table table-striped">
    <thead>
      <tr class="table-info">
        <th scope="col">Product</th>
        <th scope="col">Count</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    
    {% for item in items %}
        <tr>
            <td>
                <img src={{item.product.image.url}} class='img-thumbnail rounded' width='5%'> 
                {{ item.product.name }}
            </td>
            <td>{{ item.count }}</td>
            <td class="text-success"><i class="fa-solid fa-dollar-sign"></i> {{ item.product.price | intcomma }}</td>
        </tr>
    {% endfor %}
    <tr class="table-primary">
        <td colspan='2'>
            Total
        </td>
        <td class="text-success"><i class="fa-solid fa-dollar-sign"></i> {{ order.total | intcomma }}</td>
    </tr>
    </tbody>
</table>
<div>
    This Order Send To <span style="font-weight:500;">{{order.address.full_address}}</span>
</div>
{% endblock body %}

apps/user/templates/user/orders.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Orders{% endblock title %}

{% block body %}
    {% if orders %}
        <div class="d-flex flex-wrap">
            {% for order in orders %}
                <div class="card  col-6 p-2 bg-light border-0" style='font-size:1vw'>
                    <div class="card-body {% if order.payment_stat == 'a' %} bg-primary text-light {% elif order.payment_stat == 'p' %} bg-warning text-dark {% endif %}">
                        <p class="text-center" style='font-size:2vw;font-weight: 500;'> {{ order.id }}</p>  
                        <p>Status Order : {% if order.payment_stat == 'a' %} Awaiting Payment {% elif order.payment_stat == 'p' %} paid {% endif %}</p>
                        <p>Created At <strong>{{ order.craeted | naturaltime }}</strong></p>
                        <p>Total Price : <i class="fa-solid fa-dollar-sign"></i> {{ order.total | intcomma }}</p>
                    </div>

                    <a href="{% url 'user:order' order.id %}" class="btn btn-secondary">Detail</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
    <div class="text-center">
        <i class="text-danger fa-solid fa-xmark" style="font-size: 15vw;"></i>
        <p class="display-5">Don't Have Order</p>
    </div>
    {% endif %}
        
{% endblock body %}

apps/user/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock title %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Change' class="btn btn-primary">
    </form>

{% endblock body %}