ShopApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path("register/", RegistretionUser.as_view(), name="register"),
    path("register/verify/", VerifyCode.as_view(), name="verify_code"),
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("otp_delete/",delete_otp_codes.as_view(),name="otp-del")
]

apps/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path("checkoout/", CheckoOutView.as_view(), name="checkout"),
    path("checkout/edit/", EditItemView.as_view(), name="edit"),
]

apps/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:category_slug>/", HomeView.as_view(), name="category"),
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('profile/',ProfileView.as_view(),name='profile'),
    path('address/',AddressesView.as_view(),name='addresses'),
    path('address/create/',CreateAddresView.as_view(),name='create-address'),
    path('address/delete/<pk>/',DeleteAddressView.as_view(),name='delete-address'),
    path('order/',OredersView.as_view(),name='orders'),
    path('order/<pk>/',OrederDetailView.as_view(),name='order'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('order/', include('apps.order.urls', namespace='order')),
    path('user/', include('apps.user.urls', namespace='user')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/message.html
{% if messages %}
    {% for message in messages %}
        <div class="m-0 alert alert-{{ message.tags }}" role="alert"  style="z-index: 10;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="m-0 navbar navbar-expand-lg navbar-dark bg-dark text-light position-sticky top-0" style="z-index: 20">
    <div class="ms-auto me-auto" style="width:98%;">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <div class="nav-link">
                        <span type="button" class="dropdown-toggle" data-bs-toggle="dropdown">
                            Category
                        </span>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            
                            {% for category in categories %}
                                <li><a class="dropdown-item" href="{% url 'home:category' category.slug %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                
                
                {% if request.user.is_authenticated %}
                    <li class="ms-4 nav-item active">
                        <a class="nav-link" href="{% url 'cart:checkout' %}"><i class="{% if order_fill %}text-light{% endif %} fa-solid fa-cart-shopping"></i></a>
                    </li>
                {% endif %}
                    
            </ul>

            <ul class="navbar-nav ms-auto">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                    </li>
                {% else %}
                <div class="btn-group dropstart">
                    <li class="nav-item active me-2 bg-white text-dark p-2 rounded">
                            <span type="button" class="dropdown-toggle" id="profilebtn" data-bs-toggle="dropdown">
                                <i class="fa-solid fa-user"></i>
                                <span>{{ request.user.full_name | upper }}</span>
                            </span>
                            <ul class="dropdown-menu border" aria-labelledby="profilebtn">
                                <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:addresses' %}">Address</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:orders' %}">Orders</a></li>
                                <hr>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                                {% if request.user.is_admin %}
                                <hr>
                                <li><a class="dropdown-item bg-danger text-light" href="{% url 'account:otp-del' %}">Delete OtpCode</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </div>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>